version: "3.1"

services:
  app:
    build: .
    ports:
      - 7000:8080
    environment:
      BEANS_ENV: production
    depends_on:
      arangodb:
        condition: service_healthy

  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password
    healthcheck:
      test: wget -qO- http://localhost:8529
      interval: 100ms
      timeout: 1s
      retries: 2
    ports:
      - 8529:8529
    volumes:
      - arangodb-data:/var/lib/arangodb3
      - ./foxx:/var/lib/arangodb3-apps

volumes:
  arangodb-data:
