version: 2.1

jobs:
  build:
    docker:
      - image: arangodb/arangodb:latest
        environment:
          ARANGO_ROOT_PASSWORD: password
        command: [--server.endpoint=http+tcp://0.0.0.0:8529 --server.password password]
    steps:
      - checkout
      - run: cp config/database.json.sample config/database.json
      - run:
          name: 'Start server'
          command: ./luaonbeans.org -D .
          background: true
      - run:
          name: 'Run tests'
          command: ./luaonbeans.org -i beans specs
