version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
      - image: arangodb/arangodb:latest
        environment:
          ARANGO_ROOT_PASSWORD: password
    steps:
      - checkout
      - run: cp config/database.json.sample config/database.json
      - run:
          name: 'Wait for ArangoDB to be up'
          command: while ! nc -z localhost 8529; do sleep 1; done
      - run:
          name: 'Start Application'
          command: ./luaonbeans.org -D .
          background: true
      - run:
          name: 'Run tests'
          command: ./luaonbeans.org -i beans specs
