/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{html,js,riot,etlua}"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    // Grid classes
    'grid-cols-12',
    'gap-4',
    'col-span-12',
    'md:col-span-12',
    'lg:col-span-12',
    'col-span-11',
    'md:col-span-11',
    'lg:col-span-11',
    'col-span-10',
    'md:col-span-10',
    'lg:col-span-10',
    'col-span-9',
    'md:col-span-9',
    'lg:col-span-9',
    'col-span-8',
    'md:col-span-8',
    'lg:col-span-8',
    'col-span-7',
    'md:col-span-7',
    'lg:col-span-7',
    'col-span-6',
    'md:col-span-6',
    'lg:col-span-6',
    'col-span-5',
    'md:col-span-5',
    'lg:col-span-5',
    'col-span-4',
    'md:col-span-4',
    'lg:col-span-4',
    'col-span-3',
    'md:col-span-3',
    'lg:col-span-3',
    'col-span-2',
    'md:col-span-2',
    'lg:col-span-2',
    'col-span-1',
    'md:col-span-1',
    'lg:col-span-1',

    // Background colors
    'bg-red-50',
    'bg-blue-50',
    'bg-green-50',
    'bg-yellow-50',
    'bg-purple-50',
    'bg-pink-50',
    'bg-gray-50',
    'bg-red-100',
    'bg-blue-100',
    'bg-green-100',
    'bg-yellow-100',
    'bg-purple-100',
    'bg-pink-100',
    'bg-gray-100',
    'bg-red-200',
    'bg-blue-200',
    'bg-green-200',
    'bg-yellow-200',
    'bg-purple-200',
    'bg-pink-200',
    'bg-gray-200',
    'bg-red-300',
    'bg-blue-300',
    'bg-green-300',
    'bg-yellow-300',
    'bg-purple-300',
    'bg-pink-300',
    'bg-gray-300',
    'bg-red-400',
    'bg-blue-400',
    'bg-green-400',
    'bg-yellow-400',
    'bg-purple-400',
    'bg-pink-400',
    'bg-gray-400',
    'bg-red-500',
    'bg-blue-500',
    'bg-green-500',
    'bg-yellow-500',
    'bg-purple-500',
    'bg-pink-500',
    'bg-gray-500',
    'bg-red-600',
    'bg-blue-600',
    'bg-green-600',
    'bg-yellow-600',
    'bg-purple-600',
    'bg-pink-600',
    'bg-gray-600',

    // Border colors
    'border-red-600',
    'border-blue-600',
    'border-green-600',
    'border-yellow-600',
    'border-purple-600',
    'border-pink-600',
    'border-gray-600',

    // Text colors
    'text-red-900',
    'text-blue-900',
    'text-green-900',
    'text-yellow-900',
    'text-purple-900',
    'text-pink-900',
    'text-gray-900',
    'text-green-600',
    'text-yellow-600',
    'text-purple-600',
    'text-pink-600',
    'text-gray-600',
    'text-red-600',
    'text-blue-600',

    //hover bgcolors
    'hover:bg-red-700',
    'hover:bg-blue- 700',
    'hover:bg-green-700',
    'hover:bg-yellow-700',
    'hover:bg-purple-700',
    'hover:bg-pink-700',

    //text align
    'text-left',
    'text-center',
    'text-right',
    'text-justify',
    'text-nowrap',
    'text-wrap',
    'text-break',
    'text-ellipsis',
    'text-clip',
    'text-wrap',
  ]
};
