name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb/arangodb:latest
        env:
          ARANGO_ROOT_PASSWORD: password
        ports:
          - 8529:8529
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy database configuration
        run: cp config/database.json.sample config/database.json

      - name: Wait for ArangoDB to be up
        run: sleep 5

      - name: Start Application
        run: |
          sudo sh -c 'echo -1 > /proc/sys/fs/binfmt_misc/status'
          ./luaonbeans.org -D . -s -d
          sleep 1

      - name: Run tests
        run: ./luaonbeans.org -i beans specs

      - name: Semver Release
        uses: K-Phoen/semver-release-action@v1.3.2

